name: Download and patch(Skip version check)
env:
  GAME_ID: "com.bandainamcoent.idolmaster_gakuen"
  USER_AGENT: "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
  PLAY_EMAIL: ${{ secrets.PLAY_EMAIL }}
  AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: Get the latest version
        run: |
          TARGET_VER="$(python play_ver_check/app.py)"
          BASE_NAME="Gaku_${TARGET_VER}"
          echo "APK_VERSION=${TARGET_VER}" >> $GITHUB_ENV
          echo "GAME_FILE_BASE=${BASE_NAME}" >> $GITHUB_ENV
          echo "GAME_APK_NAME=${BASE_NAME}.apk" >> $GITHUB_ENV
          echo "GAME_CLONED_NAME=${BASE_NAME}_cloned.apk" >> $GITHUB_ENV

      - name: Download and prepare modules
        run: bash download_modules.sh

      - name: Set up JRE 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "zulu"
          java-version: "21"
          java-package: "jre"

      - name: Download and prepare APK file
        run: |
          bash play_downloader.sh ${{ env.GAME_ID }}
          java -jar APKEditor.jar m -i ${{ env.GAME_ID }} -o ${{ env.GAME_APK_NAME }}

      - name: Extract localization.json
        continue-on-error: true
        run: |
          pip install UnityPy
          python extract_localization.py "${{ env.GAME_APK_NAME }}" localization.json

      - name: Prepare cloned APK file
        run: bash clone.sh

      - name: Patch the APK files
        run: bash patch.sh

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          body: "### Gaku ${{ env.APK_VERSION }} ready to update.\nThe '_embedded' and 'cloned' apk require the included version of Localify to function.\n**Other Localify versions will NOT work.**"
          tag_name: ${{ env.APK_VERSION }}
          make_latest: true
          preserve_order: true
          files: |
            ${{ env.LOCALIFY_NAME }}
            ${{ env.PATCHED_APK }}
            ${{ env.EMBED_APK }}
            ${{ env.EMBED_APK_CLONED }}
            localization.json
